- hosts: tag_Name_K8s_master
  roles:
          - name: Configuring K8s Master
            role: /etc/ansible/K8sMultiNodeCluster/K8s-master

- hosts: tag_Name_k8s_slave

  vars_prompt:
          - name: "cluster_token"
            prompt: "Enter cluster token"
            private: no

  roles:
          - name: Configuring K8s Slave
            role: /etc/ansible/K8sMultiNodeCluster/K8s-slave

