- name: Configuring K8s repo
  yum_repository:
    name: kubernetes
    description: offical kubernetes repo
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-$basearch
    gpgcheck: yes
    gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
    enabled: yes

- name: Installing kubeadm,kubelet,kubectl,iproute-tc and Docker
  package: 
         name: "{{ item }}" 
         state: latest
  loop: "{{ packages }}"
        
- name: starting Docker and kubelet service
  service:
          name: "{{ item }}"
          enabled: yes
          state: started
  loop: "{{ services }}"

- name: Copying Docker config files 
  copy:                                 
            src: daemon.json              
            dest: /etc/docker/daemon.json

- name: restarting docker service
  service:
          name: docker
          state: restarted

- name: Copying config for bridged traffic
  copy:
        src: k8s.conf
        dest: /etc/sysctl.d/k8s.conf

- name: Restarting sysctl 
  shell: sysctl --system

- name: Fetching config images
  shell: kubeadm config images pull

- name: Starting K8s Master
  shell: kubeadm init --pod-network-cidr=10.244.0.0/16 --ignore-preflight-errors=NumCPU --ignore-preflight-errors=Mem

- name: Configuring Master as a client
  shell: mkdir -p $HOME/.kube
- name: copying file
  shell: cp -i /etc/kubernetes/admin.conf  $HOME/.kube/config
- name: configuring master
  shell: chown $(id -u):$(id -g) $HOME/.kube/config

- name: Applying flannel
  shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml

- name: Genrating Token for Slave
  shell: kubeadm token create --print-join-command
  register: token

- name: Copying token to join cluster
  debug:
          var: token.stdout_lines
