---
# tasks file for K8s-slave

- name: Configuring K8s repo
  yum_repository:
          name: kubernetes
          description: Kubernetes repo
          baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-$basearch
          gpgcheck: yes
          gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
          enabled: yes

- name: Installing kubeadm, kubelet, kubectl, iproute-tc and Docker
  package:
          name: "{{item}}"
          state: latest
  loop: "{{packages}}"

- name: starting the Docker and Kubelet service
  service:
          name: "{{item}}"
          enabled: yes
          state: started
  loop: "{{services}}"

- name: copying Docker config files
  copy:
          src: daemon.json
          dest: /etc/docker/daemon.json

- name: restart the Docker services
  service:
          name: docker
          state: restarted

- name: copying configuration for bridged traffic
  copy:
          src: k8s.conf
          dest: /etc/sysctl.d/k8s.conf

- name: Restarting sysctl
  shell: sysctl --system

- name: Joining kubernetes cluster
  shell: "{{cluster_token}}"
